# Site settings
title: Julie Vera | Portfolio
email: julie@toypig.co
description: Julie Vera's Portfolio
baseurl: "/blog/"
url: "https://julievera.github.io/portfolio" # the base hostname & protocol for your site
twitter_username: julievera
github_username:  julievera

# Build settings
markdown: redcarpet
name: blog
pygments: true
